### ISSUE TITLE
Generated pass is not loadable

### ISSUE THREAD

**Issue by trancemist** [matmartinez/covid-wallet-pass-chile#1] opened 2021-12-16 14:58 UTC
Neither iOS 15.1.1 nor MacOS 11.6.1 will recognize this as a valid pass.
iOS simply says that "Safari cannot download this file."
![IMG_4573](https://user-images.githubusercontent.com/34175312/146395166-8ed4fcf0-db3c-49fe-a48c-716a062c3fcf.jpeg)

**Comment by matmartinez** [comment] 2021-12-29 23:16
Hey there! This is odd. I'm unable to reproduce. Is this still happening to you?

Best,
Matías.

**Comment by themakunga** [comment] 2021-12-30 05:56
I tested in Mac OS Big Sur in a M1 and iPhone 11 and works perfect

**Comment by clementeross** [comment] 2022-04-02 16:50
Hey there! The process is perfect, but the Movility Pass is not added to my Apple Wallet. I use iPhone 12 with 15.3 OS version.

What could be the problem?

**Comment by clementeross** [comment] 2022-04-02 16:52
I solved the problem! With the Chrome application, the program does not work, but with Safari works perfect!

**Comment by matmartinez** [comment] 2022-04-03 01:07
I’m glad, @clementeross! I think it would be wise if I add some kind of user-agent detection to warn Chrome users. Thanks! For now, I’m closing this issue!

**Closed as completed by matmartinez** 2022-04-03 01:07 UTC

**Comment by francotc** [comment] 2022-07-26 19:45
Hi, I'm having this issue with Safari on an iPhone 11 with iOS 15.6, any workaround?
